<a href="https://colab.research.google.com/github/iamksseo/colab/blob/master/ai504_01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))
    
def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

### Scalars, Vectors, Matrices

In [ ]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

In [ ]:
print_obj(a.ndim, "a.ndim")
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")

In [ ]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")

### Tensors (N-dimensional array)

In [ ]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [ ]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

In [ ]:
# Quiz: What is the shape of [[[1], [2], [3]], [[4], [5], [6]]]?
print(np.array([[[1], [2], [3]], [[4], [5], [6]]]).shape)

### Defining Numpy arrays

In [ ]:
a = np.ones(10)
a

In [ ]:
a = np.zeros((2, 5))
a

In [ ]:
a = np.full((2,5), 5)
a

In [ ]:
a = np.random.random((2, 3, 4))
a

In [ ]:
a = np.arange(10)
a

In [ ]:
a = np.arange(10).astype(float)
a

In [ ]:
a = np.arange(10).reshape((5,2))
a

In [ ]:
# Quiz: Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0
a = np.arange(24.).reshape((4,3,2))
print(a)
print(a.shape)

### Indexing & Slicing

In [ ]:
# Indexing and slicing a vector
a = np.arange(10)
print_obj(a, "a")

print_obj(a[0], "a[0]")
print_obj(a[1], "a[1]")
print_obj(a[-1], "a[-1]")
print_obj(a[-3], "a[-3]")

print_obj(a[0:10], "a[0:10]")
print_obj(a[0:], "a[0:]")
print_obj(a[:10], "a[:10]")
print_obj(a[:], "a[:]")

print_obj(a[7:], "a[7:]")
print_obj(a[:5], "a[:5]")
print_obj(a[2:5], "a[2:5]")

# Quiz: What is a[-4:]?
print_obj(a[-4:], "a[-4:]")
# Quiz: What is a[:-8]?
print_obj(a[:-8], "a[:-8]")

print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")

print_obj(a[::-1], "a[::-1]")
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]")

# Quiz: Create [9, 6, 3] using a.

In [ ]:
# Indexing a matrix
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")

# Quiz: How to access the last row?
# Quiz: How to access the second column?
# Quiz: How to create [8, 5] using a?
a[-1:0:-1, 2]

In [ ]:
# Indexing and slicing a 3D tensor
a = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(a, "a")
# print_obj(a[2, 1, 0], "a[2, 1, 0]")

# Quiz: What would be a[0]?
# Quiz: What would be a[0, 1]?
# Quiz: Create [[0, 2, 4], [6, 8, 10]]
a[0:2, :, 0]

In [ ]:
# Conditional indexing
a = np.arange(3*2*1).reshape((3,2,1))
print_obj(a, "a")

idx = a % 2 == 0
print_obj(idx, "idx")

# Quiz: How would you create [3, 4, 5] using a?
a[idx]

In [ ]:
# Taking specific elements from a vector
a = np.arange(10)
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")

In [ ]:
# Taking specific elements from a tensor
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:,[0, 2, 3]], "a[idx]")
print_obj(a[[0, 2, 3], :], "a[idx]")
#idx = ((0,0,1,5),(1,2,0,3))
#print_obj(a[idx], "tuple indexing")
#idx = np.array([[0,0,1,5],[1,2,0,3]])
#print_obj(a[idx], "ndarray indexing")

### Math Operations

In [ ]:
# Basic operations
a = np.arange(6).reshape((3, 2))
b = np.ones((3, 2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

In [ ]:
# Unary operations
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)")
print_obj(a.sum(axis=1), "a.sum(axis=1)")

print_obj(a.mean(), "a.mean()")
print_obj(a.max(), "a.max()")
print_obj(a.min(), "a.min()")

# Quiz: Given a = np.arange(24).reshape((2,3,4)), what is the mean of the sum w.r.t to the last dimension?

In [ ]:
# Vector dot product
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")

In [ ]:
# Matrix dot product, matrix multiplication
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")
print_obj(a@b, "a @ b")

In [ ]:
# Tensor dot product, tensor multiplication
a = np.arange(24).reshape((4, 3, 2))
b = np.ones((4, 2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b).shape, "a dot b")
print_obj((a@b).shape, "a @ b")

# Quiz: what would happen if a.shape==(4,3,2) and b.shape==(2,3)?

### Shape Manipulation

In [ ]:
# Reshapes
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1))
print_obj(c, "c")

# Quiz: What would d=a.reshape((6, 4, -1)) look like?

In [ ]:
# Adding an extra dimension
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")

# Quiz: How to make a = np.ones((3,4)) into shape (3, 1, 1, 4) using reshape and None?

In [ ]:
# Stack, concatenation
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

# print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.hstack([a, b]), "a,b hstack")
# print_obj(np.hstack([a, b, a]), "a,b hstack")

# print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0")
# print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1")

# Quiz: Would concatenating two tensors whose shapes are (4, 3, 2) and (5, 4, 2) on axis=2 work?

In [ ]:
# Matrix transpose
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

In [ ]:
# Tensor transpose
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")

# b = np.transpose(a, [0, 2, 1])
# print_obj(b, "Swap axis 1 and 2")
# print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2])
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

### Broadcasting

In [ ]:
# Vector and scalar
a = np.arange(3)
b = 2.
print_obj(a, "a")

print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

In [ ]:
# Matrix and vector
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

# Quiz: What would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1, 2))?

In [ ]:
# Tensor and matrix
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

#Quiz: How can we use None to do a+b?

In [5]:
# m = 10
# n = 3
# # M = np.arange(m*n).reshape((m,n))
# M = np.random.normal(size=(m,n))
# print_obj(M, "M")

M = (np.arange(20).reshape((10,2)).astype('float') - 10.) / 10.

W = np.arange(16).reshape(8,2).astype('float') / 10

h = M.shape[0]//2
first = M[:h]
second = M[h:]
odd = M[::2]
even = M[1::2]

X = np.hstack([first, second, odd, even])
print_obj(X, "X")
print_obj(X.shape, "X.shape")                

# W = np.arange(4*n*n).reshape((4*n,n))
# W = np.random.normal(size=(4*n,n))
print_obj(W, "W")
print_obj(W.shape, "W.shape")   

Y = X @ W
print_obj(Y, "Y")
print_obj(Y.shape, "Y.shape")

print(np.mean(sigmoid(Y), axis=0))  

X:
[[-1.  -0.9  0.   0.1 -1.  -0.9 -0.8 -0.7]
 [-0.8 -0.7  0.2  0.3 -0.6 -0.5 -0.4 -0.3]
 [-0.6 -0.5  0.4  0.5 -0.2 -0.1  0.   0.1]
 [-0.4 -0.3  0.6  0.7  0.2  0.3  0.4  0.5]
 [-0.2 -0.1  0.8  0.9  0.6  0.7  0.8  0.9]]

X.shape:
(5, 8)

W:
[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]
 [1.  1.1]
 [1.2 1.3]
 [1.4 1.5]]

W.shape:
(8, 2)

Y:
[[-3.76 -4.28]
 [-1.76 -2.04]
 [ 0.24  0.2 ]
 [ 2.24  2.44]
 [ 4.24  4.68]]

Y.shape:
(5, 2)

[0.52376789 0.51783755]


### Final Quiz

In [4]:
def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following:
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (?, 4n)
# - Linearly transform X with W so that you obtain a matrix Y of shape (?, ?)
# - Put Y through the sigmoid function
# - Obtain the sum of the row-wise mean
def foo(M, W):
  h = M.shape[0]//2   # assume: M.shape[0] should be even

  first = M[:h]
  second = M[h:]
  odd = M[::2]
  even = M[1::2]

  X = np.hstack([first, second, odd, even])   # X: shape(2/M, 4n)
  Y = X @ W                                   # Y: shape(2/M, n)

  return np.mean(sigmoid(Y), axis=0).sum()

In [6]:
# for m in [2, 4, 8]:     # m: should be even
#   for n in [3, 4, 7]:   # n: whatever
#     M = np.random.normal(size=(m,n))
#     W = np.random.normal(size=(4*n,n))
#     print_obj(foo(M, W), "foo(shape(%s,%s), shape(%s,%s))" % (m, n, 4*n, n))

M = (np.arange(20).reshape((10,2)).astype('float') - 10.) / 10.
W = np.arange(16).reshape(8,2).astype('float') / 10
print_obj(foo(M, W), "foo(M, W)")    

foo(M, W):
1.0416054400726549

